param(
  [string]$Domain = "syntheye.example.com",
  [string]$LetsEncryptEmail = "admin@example.com",
  [string]$EnvFile = ".env.production",
  [switch]$Force
)

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
Set-Location $root

if ([System.IO.Path]::IsPathRooted($EnvFile)) {
  $targetPath = $EnvFile
} else {
  $targetPath = Join-Path $root $EnvFile
}

if ((Test-Path -LiteralPath $targetPath) -and -not $Force) {
  throw "Refusing to overwrite existing env file: $targetPath (use -Force to replace)"
}

function New-RandomSecret([int]$Length) {
  $chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-"
  $bytes = New-Object byte[] ($Length)
  $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
  try {
    $rng.GetBytes($bytes)
  } finally {
    $rng.Dispose()
  }
  $builder = New-Object System.Text.StringBuilder
  foreach ($b in $bytes) {
    [void]$builder.Append($chars[$b % $chars.Length])
  }
  return $builder.ToString()
}

$sessionSecret = New-RandomSecret 80
$mysqlRootPassword = New-RandomSecret 40
$mysqlAppPassword = New-RandomSecret 40
$timestampUtc = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")

$lines = @(
  "# Generated by ops/generate_prod_env.ps1 at $timestampUtc",
  "",
  "SYNTH_DOMAIN=$Domain",
  "LETSENCRYPT_EMAIL=$LetsEncryptEmail",
  "",
  "MYSQL_ROOT_PASSWORD=$mysqlRootPassword",
  "MYSQL_DATABASE=syntheye",
  "MYSQL_USER=syntheye_app",
  "MYSQL_PASSWORD=$mysqlAppPassword",
  "",
  "SYNTHEYE_ENV=production",
  "SYNTHEYE_REQUIRE_AUTH=1",
  "SYNTHEYE_SESSION_SECRET=$sessionSecret",
  "SYNTHEYE_SESSION_TTL_SECONDS=86400",
  "SYNTHEYE_SESSION_HTTPS_ONLY=1",
  "SYNTHEYE_ALLOW_ORIGINS=https://$Domain",
  "SYNTHEYE_TRUST_PROXY_HEADERS=1",
  "",
  "SYNTHEYE_DB_HOST=mysql",
  "SYNTHEYE_DB_PORT=3306",
  "SYNTHEYE_DB_USER=syntheye_app",
  "SYNTHEYE_DB_PASSWORD=$mysqlAppPassword",
  "SYNTHEYE_DB_NAME=syntheye",
  "",
  "SYNTHEYE_MAX_UPLOAD_MB=25",
  "SYNTHEYE_MAX_TEXT_CHARS=20000",
  "SYNTHEYE_RATE_LIMIT_WINDOW_SECONDS=60",
  "SYNTHEYE_RATE_LIMIT_AUTH_PER_WINDOW=20",
  "SYNTHEYE_RATE_LIMIT_ANALYZE_PER_WINDOW=60",
  "SYNTHEYE_RATE_LIMIT_GLOBAL_PER_WINDOW=240",
  "",
  "SYNTHEYE_LOG_LEVEL=INFO",
  "SYNTHEYE_LOG_FILE=/app/logs/syntheye.log"
)

Set-Content -LiteralPath $targetPath -Value $lines -Encoding UTF8
Write-Host "Created production env file: $targetPath"
Write-Host ""
Write-Host "Next:"
Write-Host "1) Validate: powershell -ExecutionPolicy Bypass -File .\ops\deploy_preflight.ps1 -EnvFile `"$EnvFile`""
Write-Host "2) Deploy  : docker compose -f docker-compose.prod.yml --env-file $EnvFile up -d --build"

if ($Domain -match "example\.com$") {
  Write-Warning "SYNTH_DOMAIN currently points to an example domain. Set your real public domain before deploying."
}
if ($LetsEncryptEmail -match "example\.com$") {
  Write-Warning "LETSENCRYPT_EMAIL currently uses an example address. Set a real mailbox for certificate alerts."
}
